name: CI



on: [push, workflow_dispatch]



jobs:


  build:



    runs-on: windows-latest



    steps:
    - name: Download NoMachine
      run: Invoke-WebRequest "https://download.nomachine.com/download/8.11/Windows/nomachine_8.11.3_3_x64.exe" -OutFile "nomachine.exe"

    - name: Install NoMachine
      run: .\nomachine.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
    - name: Run NoMachine
      run: '"C:\Program Files\NoMachine\bin\nxplayer.exe" /new -display -authentication'

    - name: Share Desktop
      run: '"C:\Program Files\NoMachine\bin\nxplayer.exe" /new -screen 0 -display -authentication'

    - name: Download


      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip


    - name: Extract


      run: Expand-Archive ngrok.zip


    - name: Auth


      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN


      env:


        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}


    - name: Enable TS


      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0


    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"


    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1


    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)


    - name: Create Tunnel


      run: .\ngrok\ngrok.exe tcp 3389
